### PR TITLE
Fix infinite loop when heightStep is 0

### PR DESCRIPTION
**Pull request by ne0fhyk**
Fixes issue https://github.com/DroidPlanner/Tower/issues/1810

### CODE REVIEW

**Comment by ne0fhyk** [comment]
@guiseco Can you do a code review for the bug fix.

**Comment by guiseco** [comment]
@ne0fhyk what about this way?

```
	double altitude = coordinate.getAltitude();
        for (int iSteps = 0; iSteps < numberOfSteps ; iSteps++) {
            CircleImpl circleImpl = new CircleImpl(missionImpl, new LatLongAlt(coordinate, (altitude)));
            circleImpl.setRadius(radius);
            list.addAll(circleImpl.packMissionItem());
	    altitude += heightStep;
      }
```

**Comment by ne0fhyk** [comment]
@guiseco Thanks for the suggestion! I updated the pull request accordingly.
Can you perform another review, thanks!

**Comment by guiseco** [comment]
@ne0fhyk  LGTM !

**Pull request merged**
